output "app_public_ip" {
  description = "Public (Elastic) IP of the app host."
  value       = aws_eip.app.public_ip
}

output "frontend_url" {
  description = "Board games search UI."
  value       = "http://${aws_eip.app.public_ip}/"
}

output "backend_url" {
  description = "Backend API base."
  value       = "http://${aws_eip.app.public_ip}:8000"
}

output "pmm_url" {
  description = "PMM monitoring UI (admin / admin1)."
  value       = "https://${aws_eip.app.public_ip}:8443/"
}

output "data_public_ip" {
  description = "Public IP of the data host (SSH/ops)."
  value       = aws_eip.data.public_ip
}

output "models_public_ip" {
  description = "Public IP of the models host (SSH/ops)."
  value       = aws_eip.models.public_ip
}

output "private_ips" {
  description = "Auto-assigned private IPs used for cross-host wiring."
  value = {
    data   = aws_network_interface.data.private_ip
    models = aws_network_interface.models.private_ip
    app    = aws_network_interface.app.private_ip
  }
}

output "ssh" {
  description = "SSH commands (key pair: var.key_name)."
  value = {
    data   = "ssh ubuntu@${aws_eip.data.public_ip}"
    models = "ssh ubuntu@${aws_eip.models.public_ip}"
    app    = "ssh ubuntu@${aws_eip.app.public_ip}"
  }
}

locals {
  # Absolute path only: demo/run.sh word-splits DEMO_SSH_OPTS, and bash does no
  # tilde expansion on the result of a parameter expansion.
  demo_ssh_opts = join(" ", concat(
    var.ssh_key_path != "" ? ["-i ${var.ssh_key_path}"] : [],
    [
      # Recreated hosts inherit the same Elastic IPs with new host keys, which
      # a remembered key turns into REMOTE HOST IDENTIFICATION HAS CHANGED.
      # These hosts are throwaway, so don't record them at all.
      "-o UserKnownHostsFile=/dev/null",
      "-o StrictHostKeyChecking=accept-new",
      "-o LogLevel=ERROR",
    ],
  ))
}

output "aws_env" {
  description = "Ready-made demo/aws.env. Write it with: terraform output -raw aws_env > ../../demo/aws.env"
  value       = <<-EOT
    # Generated by: cd deploy/aws && terraform output -raw aws_env > ../../demo/aws.env
    # demo/run.sh sources this file, so every Makefile target and demo script
    # switches to the AWS hosts at once. Delete it to go back to local compose.

    DEMO_HOST_DATA=ubuntu@${aws_eip.data.public_ip}
    DEMO_HOST_MODELS=ubuntu@${aws_eip.models.public_ip}
    DEMO_HOST_APP=ubuntu@${aws_eip.app.public_ip}

    # Where user_data cloned the repo on each host.
    DEMO_REMOTE_DIR=/opt/pl-demo

    # Instances accept EC2 key pair "${var.key_name}". Set the Terraform variable
    # ssh_key_path to have -i baked in below; absolute path or $HOME, never ~.
    DEMO_SSH_OPTS="${local.demo_ssh_opts}"

    # Note: curl targets stay http://localhost:8000 — they run ON the app host
    #
    # This file is read on your laptop only. PMM login is admin / admin1 —
    # `make prestart` re-asserts it, so skip the UI password prompt.
  EOT
}
